Console.WriteLine ("Введите первое число");
int A = Convert.ToInt32(Console.ReadLine());
Console.WriteLine ("Введите второе число число");
int B = Convert.ToInt32(Console.ReadLine());
Console.WriteLine ("Введите третье число число");
int C = Convert.ToInt32(Console.ReadLine());
int max = A;
if (B > max) max=B ;
if (C > max) max=C;
Console.WriteLine ("максимальное " + max);